[theme]
base = "light"
primaryColor = "#FEE715"
backgroundColor = "#101820"
secondaryBackgroundColor = "#49c5b6"
textColor = "#FFFFFF"
font = "sans serif"

[theme.dark]
base = "light"
primaryColor = "#ef3415"
backgroundColor = "#000000"
secondaryBackgroundColor = "#6c7b7b"
textColor = "#FFFFFF"
font = "sans serif"
