[theme]
base = "light"
primaryColor = "#FEE715"
backgroundColor = "#101820"
secondaryBackgroundColor = "#49c5b6"
textColor = "#FFFFFF"
font = "sans serif"
[theme.dark]
primaryColor = "#ff4b4b"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
font = "sans serif"
